# Generated by Django 4.2 on 2025-12-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_admin', '0003_alter_post_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
