# Generated by Django 4.2 on 2025-12-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_admin', '0005_user_blocked_users_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
