# Generated by Django 4.2 on 2025-12-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('social_admin', '0009_backfill_like_post_and_make_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reported_by', 'content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='like',
            name='object_id',
        ),
    ]
