# Generated by Django 4.2 on 2025-12-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_admin', '0011_message_typing_and_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
